gym_homepage:
    path:     /
    defaults: { _controller: GymBundle:Default:index }
gym_abonnement_create:
    path:     /abonnement/create
    defaults: { _controller: GymBundle:Default:createabonnement }
gym_client_list:
    path:     /client/list/all
    defaults: { _controller: GymBundle:Default:listclients }
gym_client_history:
    path:     /client/{id}
    defaults: { _controller: GymBundle:Default:clientHistory }
gym_abonnement_list:
    path:     /abonnement/list/all
    defaults: { _controller: GymBundle:Default:abonnementList }
gym_abonnement_archive:
    path:     /abonnement/archive
    defaults: { _controller: GymBundle:Default:abonnementArchive }